spring:
  cloud:
    gateway:
      routes:
      - id: product_route
<<<<<<< HEAD
        uri: lb://ttmall-product
=======
        uri: lb://ttmaill-product
>>>>>>> origin/master
        predicates:
          - Path=/api/product/**
        filters:
          - RewritePath=/api/(?<segment>.*),/$\{segment}

      - id: admin_route
        uri: lb://renren-fast
        predicates:
        - Path=/api/**
        filters:
        - RewritePath=/api/(?<segment>.*),/renren-fast/$\{segment}
       # - RewritePath=/api/(?<segment>/?.*),/renren-fast$\{segment}

