spring:
  cloud:
    gateway:
      routes:
      - id: third_party_route
        uri: lb://ttmall-third-party
        predicates:
        - Path=/api/thirdparty/**
        filters:
        - RewritePath=/api/thirdparty/(?<segment>/*),/$\{segment}

      - id: member_route
        uri: lb://ttmall-member
        predicates:
        - Path=/api/member/**
        filters:
        - RewritePath=/api/(?<segment>/*),/$\{segment}

      - id: ware_route
        uri: lb://ttmall-ware
        predicates:
        - Path=/api/ware/**
        filters:
        - RewritePath=/api/(?<segment>.*),/$\{segment}

      - id: product_route
        uri: lb://ttmall-product
        predicates:
        - Path=/api/product/**
        filters:
        - RewritePath=/api/(?<segment>.*),/$\{segment}

      - id: admin_route
        uri: lb://renren-fast
        predicates:
        - Path=/api/**
        filters:
        - RewritePath=/api/(?<segment>.*),/renren-fast/$\{segment}
        # - RewritePath=/api/(?<segment>/?.*),/renren-fast$\{segment}

      - id: ttmall_host_route
        uri: lb://ttmall-product
        predicates:
          - Host=**.ttmall.com

