server:
  port: 30000
spring:
  application:
    name: ttmall-third-party
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
    alicloud:
      access-key: LTAI4G8FEvBkUu9cRCXQdLSN
      secret-key: xXlqg0LWhSAiw1iZzcns3BvmzJd8rA
      oss:
        endpoint: oss-cn-beijing.aliyuncs.com
        bucket: thzc-ttmall
